services:
  - type: web
    name: ecommerce-backend
    env: python
    region: frankfurt
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi

    envVars:
      PYTHON_VERSION: 3.10
      DJANGO_SETTINGS_MODULE: ecommerce.settings
